### PR TITLE
Fix bug in Dropdown component (Issue #107)

### LINKED ISSUE #107: [BUG] Fix the warnings showing up in dev tools console regarding out-of-range values in dropdowns
**Describe the bug**
Several warnings show up on the client side due to out of range values in the dropdowns

image

**To Reproduce**
1. open the application in development environment
2. Open dev tools console

### PR DESCRIPTION
**Pull request by Ullas8296**
### What
- Fixed the warnings showing up in dev tools console regarding out-of-range values in dropdowns

### Why
- Several warnings show up on the client side dev tools console due to out of range values in the dropdowns

### How
- Moved the complex JSX logic for `renderValue` into a helper function `getRenderValue`.
- This made the main Select JSX block much cleaner and easier to read.
- Pre-computed `validValue` for the dropdown to ensure robust handling of invalid values.

### Related Issues
- Fixes #107

### CODE REVIEW

File: client/src/components/Dropdown.tsx [hunk 1]
```diff
@@ -32,16 +32,16 @@ export default function Dropdown({ sx, id, disabled, value, options, onChange, d
 
   return (
     <Select
-      value={value ?? '-'}
+      value={options?.find(option => option.value === value) ? value : ''} // Ensure value is valid
```
Comment (ishahadathb) [inline client/src/components/Dropdown.tsx:35]: Knitpick: such complex expression can be put inside the body instead of the JSX block to keep the jsx block clean & concise. It improves readability as well

Comment (Ullas8296) [reply client/src/components/Dropdown.tsx]: Hi @ishahadathb is it fine now?

**Review by ali-ahnaf — APPROVED** [review]
